apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-frontend
  labels:
    {{- include "todo-app.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
  - port: {{ .Values.service.frontend.port }}
    targetPort: {{ .Values.service.frontend.targetPort }}
    protocol: TCP
    name: http
    {{- if and (eq .Values.service.frontend.type "NodePort") .Values.service.frontend.nodePort }}
    nodePort: {{ .Values.service.frontend.nodePort }}
    {{- end }}
  selector:
    {{- include "todo-app.frontend.selectorLabels" . | nindent 4 }}
