{{- if .Values.dapr.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kafka-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  KAFKA_SASL_USERNAME: {{ .Values.secrets.KAFKA_SASL_USERNAME | b64enc | quote }}
  KAFKA_SASL_PASSWORD: {{ .Values.secrets.KAFKA_SASL_PASSWORD | b64enc | quote }}
{{- end }}
